### ISSUE TITLE
Question regarding filter of words appearing in only one patent

### ISSUE THREAD

**Issue by larsvancutsem** [sam-arts/respol_patents_code#1]
Dear Sam, Jianan and Juan Carlos,
First of all, congratulations on the publication & thank you very much for making the code and data publicly available!
With regard to my question:
I was wondering why one would filter out words appearing in only one patent? Might this be for robustness reasons?
Best,
Lars

**Comment by sam-arts** [comment]
Dear Lars,

Thank you for your interest in our work. Most studies in this area exclude words which appear in more than x% of all documents or in less than x% of all documents. We decided to exclude words which appear in only one patent because these words are likely to be spelling errors etc.

Best,
Sam



Prof. dr. Sam Arts
Associate Professor of Strategy
Faculty of Economics and Business
KU Leuven
Tel: +32 3 201 18 36
e-mail: ***@***.******@***.***>
https://sites.google.com/view/samarts

**Comment by larsvancutsem** [comment]
Thank you for your swift answer!
